### ISSUE TITLE
Indicator implementation 

### ISSUE THREAD

**Issue by vivekpchand** [Kaycaul/Cart-Game#10]
Indicators for obstacles on track

**Comment by Kaycaul** [comment]
with a distance warning? or it flashes as you get close?

**Comment by Kaycaul** [comment]
idea: instead of indicators, just color the road with stripes before each obstacle

**Comment by Kaycaul** [comment]
@vivekpchand we might not need this if the camera is zoomed out enough, you can close the issue as not planned if you agree
