### ISSUE TITLE
more obstacles

### ISSUE THREAD

**Issue by Kaycaul** [Kaycaul/Cart-Game#72]

**Comment by Kaycaul** [comment]
![fire](https://user-images.githubusercontent.com/84094849/229915288-563e8a15-573a-494c-b6e7-c5ddc8be74d6.png)
![bluecone](https://user-images.githubusercontent.com/84094849/229915325-219da553-eb6a-414c-a593-719494ca9fa3.png)

**Comment by wang-i** [comment]
melted chocolate ice cream cones
they should play the cartoon slip noise when you hit them lol

**Comment by Kaycaul** [comment]
![cone](https://user-images.githubusercontent.com/84094849/230382753-0f48b1b0-6aee-4362-8adc-7433ef3841c0.png)
